In [1]:
import sklearn.datasets as datasets
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

/home/carbon13/miniconda2/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/carbon13/miniconda2/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
path='/home/carbon13/machine_learning_study_follow_yincheng-master/decision_tree/lenses.txt'

In [38]:
data=pd.read_table(path,header=None)

/home/carbon13/miniconda2/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [4]:
data.info

<bound method DataFrame.info of              0      1    2        3          4
0        young  myope   no  reduced  no lenses
1        young  myope   no   normal       soft
2        young  myope  yes  reduced  no lenses
3        young  myope  yes   normal       hard
4        young  hyper   no  reduced  no lenses
5        young  hyper   no   normal       soft
6        young  hyper  yes  reduced  no lenses
7        young  hyper  yes   normal       hard
8          pre  myope   no  reduced  no lenses
9          pre  myope   no   normal       soft
10         pre  myope  yes  reduced  no lenses
11         pre  myope  yes   normal       hard
12         pre  hyper   no  reduced  no lenses
13         pre  hyper   no   normal       soft
14         pre  hyper  yes  reduced  no lenses
15         pre  hyper  yes   normal  no lenses
16  presbyopic  myope   no  reduced  no lenses
17  presbyopic  myope   no   normal  no lenses
18  presbyopic  myope  yes  reduced  no lenses
19  presbyopic  myope  yes  

In [39]:
dict1={'young':0,'pre':1,'presbyopic':2}
data[0]=data[0].map(dict1)

In [40]:
dict2={'myope':0, 'hyper':1}
data[1]=data[1].map(dict2)
data[1].unique()

array([0, 1])

In [41]:
dict3={'no':0, 'yes':1}
data[2]=data[2].map(dict3)
data[2].unique()

array([0, 1])

In [42]:
dict4={'reduced':0, 'normal':1}
data[3]=data[3].map(dict4)
data[3].unique()

array([0, 1])

In [43]:
dict5={'no lenses':0, 'soft':1, 'hard':2}
data[4]=data[4].map(dict5)
data[4].unique()

array([0, 1, 2])

In [46]:
data

0  1  2  3  4
0   0  0  0  0  0
1   0  0  0  1  1
2   0  0  1  0  0
3   0  0  1  1  2
4   0  1  0  0  0
5   0  1  0  1  1
6   0  1  1  0  0
7   0  1  1  1  2
8   1  0  0  0  0
9   1  0  0  1  1
10  1  0  1  0  0
11  1  0  1  1  2
12  1  1  0  0  0
13  1  1  0  1  1
14  1  1  1  0  0
15  1  1  1  1  0
16  2  0  0  0  0
17  2  0  0  1  0
18  2  0  1  0  0
19  2  0  1  1  2
20  2  1  0  0  0
21  2  1  0  1  1
22  2  1  1  0  0
23  2  1  1  1  0

In [50]:
x_train,x_test,y_train,y_test=train_test_split(data.iloc[:,0:4],data[4])

In [47]:
x_test

0  1  2  3
13  1  1  0  1
18  2  0  1  0
12  1  1  0  0
11  1  0  1  1
7   0  1  1  1
1   0  0  0  1

In [48]:
x_train

0  1  2  3
8   1  0  0  0
9   1  0  0  1
10  1  0  1  0
2   0  0  1  0
19  2  0  1  1
21  2  1  0  1
20  2  1  0  0
17  2  0  0  1
14  1  1  1  0
0   0  0  0  0
5   0  1  0  1
3   0  0  1  1
15  1  1  1  1
22  2  1  1  0
6   0  1  1  0
16  2  0  0  0
4   0  1  0  0
23  2  1  1  1

In [49]:
y_train

13    1
18    0
12    0
11    2
7     2
1     1
Name: 4, dtype: int64

In [25]:
tree=DecisionTreeClassifier()

In [51]:
tree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [52]:
tree.score(x_test,y_test)

1.0